name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          python manage.py test

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}   
               
  
      - name: Build and load Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.ECR_REPOSITORY_URL }}/backend:${{ github.sha }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.ECR_REPOSITORY_URL }}/backend:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to ECR
        if: success()
        run: |
          cd backend
          docker push ${{ secrets.ECR_REPOSITORY_URL }}/backend:${{ github.sha }}
